apiVersion: v1
kind: Service
metadata:
  name: capstone-service
spec:
  type: LoadBalancer
  selector:
    app: capstone
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 3000

      apiVersion: v1
