apiVersion: v1
kind: Service
metadata:
  name: capstone-service
  namespace: capstone
spec:
  selector:
    app.kubernetes.io/name: capstone
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 3000