apiVersion: v1
kind: Service
metadata:
  name: capstone-service
  namespace: capstone
spec:
  type: LoadBalancer
  selector:
    app: capstone
  ports:
    - name: capstone-port
      protocal: TCP
      port: 8089
      targetPort: 3000
